--! COMPILED BY NENE :)

--TODO: Create SQL queries to ... 
-- (1) create all tables
-- (2) insert seed data
-- (3) manipulate data 

--* (1) CREATE ALL TABLES
 
-- Create tables without fk's:
CREATE TABLE IF NOT EXISTS dd_classes (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
class_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS dd_prog_weeks(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  week_num INT
);

CREATE TABLE IF NOT EXISTS dd_workouts(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  workout_type VARCHAR(255),
  day_num INT,
  is_rest BOOLEAN
);

CREATE TABLE IF NOT EXISTS dd_exercises(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  exercise_name VARCHAR(255),
  exercise_xp INT,
  sets INT, 
  reps INT, 
  rest_time INT 
);

-- Create tables with fk's:
CREATE TABLE IF NOT EXISTS dd_users (
  clerk_id TEXT PRIMARY KEY,
  username VARCHAR(255),
  gender VARCHAR(255),
  age INT,
  weight INT,
  bio TEXT,
  prog_start_date DATE,
  classes_id_fk INT REFERENCES dd_classes(id) --foreign key
);

CREATE TABLE IF NOT EXISTS dd_prog (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  duration_weeks INT,
  classes_id_fk INT REFERENCES dd_classes(id) --foreign key
);

CREATE TABLE IF NOT EXISTS dd_progression (
   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   total_xp INT,
   level INT,
  user_id_fk TEXT REFERENCES dd_users(clerk_id) --foreign key
);

-- Create junction tables:
CREATE TABLE IF NOT EXISTS jctn_dd_prog_dd_prog_weeks (
 weeks_id_fk INT REFERENCES dd_prog_weeks(id), --foreign key
 prog_id_fk INT REFERENCES dd_prog(id), --foreign key
 PRIMARY KEY (weeks_id_fk, prog_id_fk)
);

CREATE TABLE IF NOT EXISTS jctn_dd_prog_weeks_dd_workouts (
 workouts_id_fk INT REFERENCES dd_workouts(id), --foreign key
 weeks_id_fk INT REFERENCES dd_prog_weeks(id), --foreign key
 PRIMARY KEY (workouts_id_fk, weeks_id_fk)
);

CREATE TABLE IF NOT EXISTS jctn_dd_workouts_dd_excercises (
 workouts_id_fk INT REFERENCES dd_workouts(id), --foreign key
 exercises_id_fk INT REFERENCES dd_exercises(id), --foreign key
 PRIMARY KEY (workouts_id_fk, exercises_id_fk)
);

--! ----------------------------------------------------------------

--* (2) INSERT SEED DATA
-- seed queries - regular tables;
INSERT INTO dd_classes (class_name) VALUES --id is auto-generated
('testClass')

INSERT INTO dd_users (clerk_id, username, gender, age, weight, bio, prog_start_date, classes_id_fk) VALUES --clerk_id is NOT auto-generated, fk is NOT autogenerated
('testId','testAccount', 'female', 30, 100, 'this is my testBio - why is test, who is test, when is test', '2026-02-16', 1)

INSERT INTO dd_exercises (exercise_name, exercise_xp, is_rest, sets, reps, rest_time) VALUES --id is auto-generated
('testExercise', 100, true, 5, 8, 30)

INSERT INTO dd_workouts (workout_type, day_num, is_rest) VALUES --id is auto-generated
('testWorkout', 1, false)

INSERT INTO dd_progression (total_xp, level, user_id_fk) VALUES --id is auto-generated, fk it NOT auto-generated(must match a user in dd_users)
(1000, 2, 'testClerkId')

INSERT INTO dd_prog (duration_weeks, classes_id_fk) VALUES --id is auto-generated, fk it NOT auto-generated(must match a user in dd_users)
(6, 1)

INSERT INTO dd_prog_weeks (week_num) VALUES --id is auto-generated
(3)

-- seed queries - junction tables;
INSERT INTO jctn_dd_prog_dd_prog_weeks ( weeks_id_fk, prog_id_fk ) VALUES
(1, 1)

INSERT INTO jctn_dd_prog_weeks_dd_workouts ( workouts_id_fk, weeks_id_fk ) VALUES
(1, 1)

INSERT INTO jctn_dd_workouts_dd_excercises ( workouts_id_fk, exercises_id_fk) VALUES
(1, 1)